WIP: RFC8183 publisher request repository response
RIPE-NCC/rpki-commons pull request #110
Opened 2022-02-17 15:20 UTC by erikrozendaal

Implementation of RFC8183 `publisher_request` and `repository_response` classes and XML mapping.

 * [ ] Unit tests
 * [ ] I have updated the changelog in README.md

2022-02-22 14:01 UTC, wibisono approved these changes

2022-02-23 12:29 UTC, ties requested changes
Probably better to also check for empty strings for the values that are actually really require. Will go over those now.

2022-02-23 12:29 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponse.java
> +        this.tag = Objects.requireNonNull(tag, "tag must not be null");
For a few of those: `Strings.isNullOrEmpty` may be better.

2022-02-23 12:29 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequestSerializer.java
> +                    .map(bpkiTa -> getProvisioningIdentityCertificate(bpkiTa))
Implicit: base64 decode happens there.

2022-02-23 12:29 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponseSerializer.java
> +                    .map(bpkiTa -> getProvisioningIdentityCertificate(bpkiTa))
Same

2022-02-24 15:12 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequestSerializer.java
> +                    .map(bpkiTa -> getProvisioningIdentityCertificate(bpkiTa))
It throws `IllegalArgumentException ` from decode which is caught here, so I guess, it's ok.

2022-02-24 15:13 UTC, lolepezy approved these changes

2022-02-24 16:31 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/PublisherRequestSerializer.java
> +                    .map(bpkiTa -> getProvisioningIdentityCertificate(bpkiTa))
Yeap. I was not sure it checked that it was valid base64 but it does so implicitly

2022-02-24 16:31 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/RepositoryResponse.java
> +        this.tag = Objects.requireNonNull(tag, "tag must not be null");
Scratch that.

2022-02-24 16:32 UTC, ties approved these changes

2022-02-24 16:33 UTC, lolepezy approved these changes

2022-02-24 16:38 UTC, merged