Support ASPA CMS objects based on draft standard and sidrops mailing list
RIPE-NCC/rpki-commons pull request #111
Opened 2022-03-28 13:11 UTC by erikrozendaal

See https://datatracker.ietf.org/doc/html/draft-ietf-sidrops-aspa-profile-07 and https://mailarchive.ietf.org/arch/msg/sidrops/oZqEFK4PBfolj_W6iBlAvlX-SlA/

  * [X] I have updated the changelog in README.md

2022-03-31 08:26 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +public class ASProviderAttestationCms extends RpkiSignedObject {
In this case I just copied the name from the RFC. Type completion (by typing `A-S-P-A`) works for this. But I also don't mind using `AspaCms`.

2022-03-31 08:27 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +    private ImmutableSortedSet<ProviderAS> providerASSet;
Mainly to to achieve some level of determinism. Encoding/printing will now always use a well defined order (just like `IpResourceSet`), which makes things easier to debug and less error-prone.

2022-03-31 12:17 UTC, ties requested changes

2022-03-31 12:17 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +public class ASProviderAttestationCms extends RpkiSignedObject {
I prefer the long name

2022-03-31 12:17 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +        this.customerAsn = Objects.requireNonNull(customerAsn);
Could also use `@NonNull` here instead

2022-03-31 12:17 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +        String location = "unknown.gbr";
```suggestion
        String location = "unknown.asa";
```

2022-03-31 12:17 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +            new DERSequence(providerASSet.stream().map(as -> {
We may need to reject the case of 0 ProviderAs
```
        Preconditions.checkState(providerASSet.size() > 0);
```

2022-03-31 12:17 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +            validationResult.rejectIfFalse(index < itemCount && seq.getObjectAt(index) instanceof ASN1Integer, ValidationString.ASPA_CUSTOMER_ASN_PRESENT);
Check the CodeQl warning please

2022-03-31 12:26 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +            validationResult.rejectIfFalse(index < itemCount && seq.getObjectAt(index) instanceof ASN1Integer, ValidationString.ASPA_CUSTOMER_ASN_PRESENT);
The warning is: `Condition 'index < itemCount' is always 'true'`. I disagree with removing this bounds check, since there is quite a bit of code between the previous bounds check and the array access here. People may refactor this code and then get a runtime exception instead of a validation error.

2022-03-31 12:49 UTC, erikrozendaal commented on src/test/java/net/ripe/rpki/commons/crypto/util/CertificateRepositoryObjectFactoryTest.java
> +    public void shouldParseMalformedGhostbustersRecord() {
Typo fix for previously existing test method (boy scout)

2022-03-31 13:44 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +public class ASProviderAttestationCms extends RpkiSignedObject {
The RoaCms should be called RouteOriginAttestationCms as well.

2022-03-31 13:55 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +    private ImmutableSortedSet<ProviderAS> providerASSet;
Since we only care about some stable order, can we then generate some Comparable instance for it with Lombok or something under the hood?

2022-03-31 14:39 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +                validationResult.rejectIfFalse(version.intValueExact() == 0, ValidationString.ASPA_VERSION, String.valueOf(version.intValueExact()));
I guess we should also abort parsing if this happens (so return?)

2022-03-31 14:39 UTC, ties commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +            validationResult.rejectIfFalse(index < itemCount && seq.getObjectAt(index) instanceof ASN1Integer, ValidationString.ASPA_CUSTOMER_ASN_PRESENT);
:+1:

2022-04-01 07:46 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +public class ASProviderAttestationCms extends RpkiSignedObject {
Renamed to `AspaCms`

2022-04-01 13:27 UTC, lolepezy approved these changes

2022-04-04 07:06 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +    private ImmutableSortedSet<ProviderAS> providerASSet;
I can't find anything in Lombok that automatically generates this. Also, the sorting order as defined here is pretty "natural", as it is the lexicographical ordering of the individual fields.

2022-04-04 07:06 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ProviderAS.java
> +        if (Objects.equals(this.afiLimit, that.afiLimit)) {
See below.

2022-04-04 07:07 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCms.java
> +        this.customerAsn = Objects.requireNonNull(customerAsn);
Done. Didn't know this annotation actually inserted null-checks, nice!

2022-04-04 07:08 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsBuilder.java
> +            new DERSequence(providerASSet.stream().map(as -> {
Done

2022-04-04 07:09 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +            this.providerASSet = StreamSupport.stream(providerAsnsSequence.spliterator(), false)
Added a validation check, so empty provider AS set is rejected now.

2022-04-04 07:10 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +                validationResult.rejectIfFalse(version.intValueExact() == 0, ValidationString.ASPA_VERSION, String.valueOf(version.intValueExact()));
Normally we try to perform as many validation checks as possible, even when certain checks already failed. Only when you try to access the resulting object do we throw an error if a validation check failed. Since there are no more validations here that depend on the result of this validation there is no need to return.

2022-04-04 10:22 UTC, wibisono approved these changes

2022-04-04 11:38 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +                return;
Good catch! Added error message in this case.

2022-04-04 11:39 UTC, erikrozendaal commented on src/test/java/net/ripe/rpki/commons/crypto/cms/aspa/AspaCmsTest.java
> +        assertEquals(providerAsSet, cms.getProviderASSet());
`createAspa` uses the builder class and builders always generate the ASN.1 encoding and then use the parser to decode the result.

2022-04-04 11:39 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/cms/aspa/ASProviderAttestationCmsParser.java
> +                validationResult.rejectIfFalse(tagged.getTagNo() == 0, ValidationString.ASPA_CONTENT_STRUCTURE);
Added a comment here about this case.

2022-04-04 15:21 UTC, merged