Fix a number of CodeQL nits
RIPE-NCC/rpki-commons pull request #113
Opened 2022-04-13 06:25 UTC by ties

* [ ] I have updated the changelog in README.md

2022-04-21 12:07 UTC, erikrozendaal requested changes

2022-04-21 12:07 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/crl/X509Crl.java
> +    public static class Entry implements Comparable<Entry>, Serializable {
`EqualsSupport` also includes a `toString` implementation, so lombok's `@ToString` should be added as well. In this case, `@Value` is even better since `Entry` is an immutable value class anyway.

2022-04-21 12:07 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/crypto/rfc3779/AddressFamily.java
> +public class AddressFamily implements Comparable<AddressFamily>, Serializable {
We can use `@Value` for this class as well.

2022-04-22 07:10 UTC, ties commented
@erikrozendaal should be done. Not sure about the `serialVersionUID`. Since there is no functional change in the API i kept it the same as before the changes.

2022-04-22 08:04 UTC, erikrozendaal commented
`serialVersionUID` is not something we really care about at the moment. I think the classes are only serializable due to the use in wicket sessions at some point. With the change of the class hierarchy they are no longer compatible w.r.t. serialization, but that shouldn't affect us.

2022-04-22 13:52 UTC, merged