Property test improvements
RIPE-NCC/rpki-commons pull request #117
Opened 2022-09-20 21:25 UTC by jcoultas

This pull request increases coverage on property tests by ensuring a test exercises code that was not previously encountered.  By adding a URI generator and adding crl distribution points to the **validParentChildSubResources** property test, overall coverage is improved.

I am a part of a research group at the University of Illinois Chicago that works towards novel methods to detect bugs in software projects. This project is identified as being a good candidate for application of our research method to improve coverage using property tests. The above issue outlines the findings with a pull request of the enhanced property test to document the observed behavior.

  * [ ] I have updated the changelog in README.md

2022-11-22 22:59 UTC, jcoultas commented
Code review requested please - @dacruz, @erikrozendaal , @chrisamin , @ties .  Thank you!

2022-11-29 13:05 UTC, erikrozendaal requested changes
Hi @jcoultas,

Sorry for the late review and thanks for your contribution. URI testing has not been a big focus of this project so it can definitely be improved. Please see the feedback comments what is needed to get this merged. Let us know if you have any questions.

Regards, Erik

2022-12-02 20:32 UTC, jcoultas commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +    public final int HIER_PATH_ABSOLUTE = 1;
For the hostname, are IPv4 or IPv6 addresses allowed?  Or just hostnames?

2022-12-02 22:08 UTC, jcoultas commented on src/test/java/net/ripe/rpki/commons/validation/X509ResourceCertificateParentChildValidatorTest.java
> +    public void validParentChildSubResources(List<@From(IpResourceGen.class) IpResource> parentResources, int childResourceCount, @Size(min=0, max=1000) List<@From(URIGen.class) URI> crlUris) throws
Moved this into `X509ResourceCertificateParserTest` as `validURI` that has two generators that accept the protocol as parameters.

2022-12-02 22:09 UTC, jcoultas commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +        String[] commonScheme = { "http", "https", "ftp", "ftps", "mailto", "file", "data", "irc", "blob", "sftp" };
Updated in validURI.

2022-12-02 22:09 UTC, jcoultas commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +    public final int HIER_PATH_ABSOLUTE = 1;
Updated to use absolute path.  Currently uses hostname, IPv4, and IPv6 addresses, but let me know if IP addresses are not allowed.

2022-12-02 22:10 UTC, jcoultas commented
@erikrozendaal I think that I have addressed the items pointed out in the above comments.  Please review and let me know of any additional changes.

2022-12-03 19:10 UTC, ties commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +    public final int HIER_PATH_ABSOLUTE = 1;
I think IPv4 and IPv6 addresses are allowed.

I know some implementations disallow port numbers, but can not find a reference in RFCs for that. TLS certificates for (public) IP addresses are also possible. I don't think this has been deployed in practice though.

The RFCs appears to be have no clear restrictions on the content of the URIs. I quickly checked [rfc6487#4.8.8](https://www.rfc-editor.org/rfc/rfc6487#section-4.8.8), [rfc6481#2.2](https://www.rfc-editor.org/rfc/rfc6481.html#section-2.2), [rfc81812#3.2](https://www.rfc-editor.org/rfc/rfc8182.html#section-3.2)

2022-12-08 01:45 UTC, jcoultas commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +    public final int HIER_PATH_ABSOLUTE = 1;
OK cool.  Thanks for checking that.  Any additional feedback or changes for this PR?

2022-12-08 07:11 UTC, ties commented on src/test/java/net/ripe/rpki/commons/validation/properties/URIGen.java
> +    public final int HIER_PATH_ABSOLUTE = 1;
I think it looks good.

2022-12-08 13:28 UTC, erikrozendaal commented
Thanks @jcoultas , looks good!

2022-12-08 13:29 UTC, erikrozendaal approved these changes

2022-12-08 13:29 UTC, merged