Add isCmsBased for Object Type enum
RIPE-NCC/rpki-commons pull request #140
Opened 2023-11-01 13:01 UTC by ties

* [x] I have updated the changelog in README.md

2023-11-01 14:00 UTC, lolepezy approved these changes

2024-01-10 14:41 UTC, lolepezy requested changes

2024-01-10 14:41 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/util/RepositoryObjectType.java
> +        if (name.equals(".tak")) {
Also `endsWith`? Or did you mean something else here?

2024-01-10 14:41 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/util/RepositoryObjectType.java
> +    private boolean isCmsBased;
Where do you expect it to be used? 
It may be that the same can be achieved by the `<T extends RpkiSignedObject>`  hierarchy

2024-01-10 15:31 UTC, ties commented on src/main/java/net/ripe/rpki/commons/util/RepositoryObjectType.java
> +        if (name.equals(".tak")) {
Good catch. Added a test for that

2024-01-10 15:33 UTC, ties commented on src/main/java/net/ripe/rpki/commons/util/RepositoryObjectType.java
> +    private boolean isCmsBased;
I use the repositoryObjectType thing before deciding what parser to use. The `CertificateRepositoryObjectFactory` can not be used if the file type is not understood by the lib yet (such as RSC/TAK atm).

It just makes some switch statements a bit nice.

2024-01-10 15:41 UTC, lolepezy approved these changes

2024-01-10 16:34 UTC, merged