Rm xstream
RIPE-NCC/rpki-commons pull request #36
Opened 2020-12-03 08:12 UTC by dacruz

2020-12-03 08:57 UTC, bjpbakker commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        return node.getAttributes().getNamedItem(attr).getTextContent();
This possibly throws a NPE. I suggest to either return `Optional<String>` or throw a different exception when the attribute is not present.

2020-12-03 08:57 UTC, bjpbakker commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +    protected String toString(final Document document) throws TransformerException {
What was wrong with `serialize`? In java `toString` is a bit misleading IMO because the regular `Object.toString()` is used for debugging purposes, and should not be relied upon for stable outputs.

2020-12-03 08:57 UTC, bjpbakker commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentity.java
> +    private final int version = VERSION;
Why not use `VERSION` instead?

2020-12-03 11:12 UTC, wibisono commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            final InputSource is = new InputSource();
Maybe try with resource would not hurt here?

2020-12-03 11:52 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +    protected String toString(final Document document) throws TransformerException {
Good point. I can change it to something else. But if it is serialize, we would have an:
`public abstract String serialize(T object)` and `protected String serialize(Document document)`

2020-12-03 11:55 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            final InputSource is = new InputSource();
What do you mean?

2020-12-03 12:33 UTC, wibisono commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            final InputSource is = new InputSource();
Make sure it's [cleanly close](https://www.baeldung.com/java-try-with-resources) in case something goes wrong?  Not sure if it's needed.

2020-12-03 16:32 UTC, ties requested changes

2020-12-03 16:32 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        final DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
Likely vulnerable to XML External Entity processing issues, see https://rules.sonarsource.com/java/RSPEC-2755

2020-12-03 16:32 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            childBpkiTaElement.setTextContent(Base64.getEncoder().encodeToString(childIdentity.getIdentityCertificate().getEncoded()));
We could add `getBase64` to `AbstractX509CertificateWrapper`?

2020-12-03 16:32 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializerException.java
> +public class IdentitySerializerException extends RuntimeException {
2-3 line javadoc on when to use this type would help me 👍

2020-12-03 16:32 UTC, ties commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentitySerializer.java
> +            final DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
in general: Would be good to have one utility that creates a correctly configured DocumentBuilderFactory

2020-12-03 16:32 UTC, ties commented on src/test/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializerTest.java
> +            "<ns0:child_request xmlns:ns0=\"http://www.hactrn.net/uris/rpki/rpki-setup/\" child_handle=\"Bob\" version=\"2\" tag=\"1234\">\n" +
Could this influence compatibility?

2020-12-03 16:32 UTC, ties commented on pom.xml
> +            <version>8.7</version>
The jing dependency pulls in an old version of saxon. The jing dependency is from 2010. Perhaps we can change that out instead?

2020-12-04 12:48 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        final DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
Added `documentFactory.setFeature(XMLConstants.FEATURE_SECURE_PROCESSING, true);`

2020-12-04 13:44 UTC, dacruz commented on src/test/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializerTest.java
> +            "<ns0:child_request xmlns:ns0=\"http://www.hactrn.net/uris/rpki/rpki-setup/\" child_handle=\"Bob\" version=\"2\" tag=\"1234\">\n" +
Yes, it could. But it should be child_handle at least since 2013... So I think it is time for 'them' to fix it...

2020-12-07 08:31 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        return node.getAttributes().getNamedItem(attr).getTextContent();
I've added the Optional, can you check again?

2020-12-07 08:31 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +    protected String toString(final Document document) throws TransformerException {
Done...

2020-12-07 08:31 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentity.java
> +    private final int version = VERSION;
Hahaha... Done!

2020-12-07 08:33 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            final InputSource is = new InputSource();
I'm closing it now, although it is not required for StringReader.

2020-12-07 08:34 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            childBpkiTaElement.setTextContent(Base64.getEncoder().encodeToString(childIdentity.getIdentityCertificate().getEncoded()));
I've moved it somewhere else...

2020-12-07 08:35 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializerException.java
> +public class IdentitySerializerException extends RuntimeException {
I've moved the exception into IdentitySerializer. I think that makes it clean its relation to.

2020-12-07 08:36 UTC, dacruz commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentitySerializer.java
> +            final DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
I had it already, just not used here. I've fixed it.

2020-12-07 08:37 UTC, dacruz commented on pom.xml
> +            <version>8.7</version>
I've bumped it to v10.3.

2020-12-15 10:22 UTC, lolepezy requested changes

2020-12-15 10:22 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ChildIdentitySerializer.java
> +            characterStream.close();
Use  try-with-resources?

2020-12-15 10:22 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        return Optional.ofNullable(node.getAttributes())
I guess you meant to say 
```
return Optional.ofNullable(node.getAttributes())
                .flatMap(a -> Optional.ofNullable(a.getNamedItem(attr)))
                .map(item->item.getTextContent());
```
?
Otherwise it's equivalent to 
```
return Optional.ofNullable(node.getAttributes())
                .map(a -> a.getNamedItem(attr).getTextContent());
```
and NPE can still happen as "null.getTextContent()".

2020-12-15 10:22 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        return getElement(doc, nodeName).map(e -> e.getTextContent().replaceAll("\\s+", ""));
Same here, NPE in case of empty textContent.

2020-12-15 10:22 UTC, lolepezy commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentitySerializer.java
> +            characterStream.close();
Same, try-with-resource.

2020-12-16 15:40 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        final DocumentBuilderFactory documentFactory = DocumentBuilderFactory.newInstance();
I think the spec @ties mentioned actually says you should avoid that one and use the following: 

```java
df.setAttribute(XMLConstants.ACCESS_EXTERNAL_DTD, ""); // Compliant
df.setAttribute(XMLConstants.ACCESS_EXTERNAL_SCHEMA, ""); // compliant
```

I'm not sure why they recommend against setting `FEATURE_SECURE_PROCESSING` also (although it should be the default by now).

2020-12-16 15:40 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/IdentitySerializer.java
> +        return parser.getCertificate();
This may throw an `IllegalArgumentException` if the certificate failed validation. Might be cleaner to check for `validationResult.hasFailures()` first.

2020-12-16 15:40 UTC, erikrozendaal commented on src/main/java/net/ripe/rpki/commons/provisioning/identity/ParentIdentity.java
> +    private ProvisioningIdentityCertificate parentIdCertificate;
These should all be `final`

2020-12-23 14:14 UTC, wibisono approved these changes

2020-12-23 14:18 UTC, merged